import { useState } from "react";
import { toast } from "sonner";
import {
  ShieldCheck,
  Code2,
  Terminal,
  Mic,
  GitCommit,
  CheckCircle2,
  Copy,
  ExternalLink,
  Flame,
  Filter,
  Play,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  loadProofArtifacts,
  analyzeTutorialHell,
  type ProofArtifact,
  type ProofArtifactType,
} from "@/lib/proof-wall";
import { loadKernelState } from "@/lib/kernel";

export function ProofWallView() {
  const kernel = loadKernelState();
  const [artifacts] = useState<ProofArtifact[]>(loadProofArtifacts());
  const [filter, setFilter] = useState<string>("all");

  const tutorialHell = analyzeTutorialHell(kernel.buildTimeSeconds7d, kernel.watchTimeSeconds7d);

  const filtered = artifacts.filter((a) => {
    if (filter === "all") return true;
    return a.type === filter;
  });

  const handleCopySha = (sha: string) => {
    navigator.clipboard.writeText(sha);
    toast.success("Receipt Token Copied", {
      description: `Cryptographic proof ${sha} copied to clipboard.`,
    });
  };

  const getIcon = (type: ProofArtifactType) => {
    switch (type) {
      case "code_execution":
        return <Code2 className="h-4 w-4 text-emerald-500" />;
      case "terminal_session":
        return <Terminal className="h-4 w-4 text-sky-500" />;
      case "mock_interview":
        return <Mic className="h-4 w-4 text-purple-500" />;
      case "git_commit":
        return <GitCommit className="h-4 w-4 text-amber-500" />;
      default:
        return <ShieldCheck className="h-4 w-4 text-primary" />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Proof Wall Header */}
      <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-display text-lg font-bold tracking-tight">
                  Proof-of-Work Wall (Verifiable Artifacts)
                </h3>
                <Badge
                  variant="outline"
                  className="font-mono text-[10px] text-emerald-600 border-emerald-500/30"
                >
                  ANTI-RESUME ACTIVE
                </Badge>
              </div>
              <p className="mt-0.5 text-xs text-muted-foreground">
                Chronological proof receipts generated by test runs, terminal sessions, and mock
                interviews. Real output, zero tutorial fluff.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              className="font-mono text-xs"
              onClick={() => {
                const url = window.location.origin + "/p/student";
                navigator.clipboard.writeText(url);
                toast.success("Public Proof Link Copied!", {
                  description:
                    "Share your verifiable proof wall instead of a self-declared resume.",
                });
              }}
            >
              <ExternalLink className="mr-1.5 h-3.5 w-3.5" />
              Share Proof Wall
            </Button>
          </div>
        </div>

        {/* Tutorial Hell Gauge */}
        <div className="mt-5 rounded-xl border border-border/80 bg-muted/40 p-4">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-2">
              <Flame
                className={`h-4 w-4 ${tutorialHell.isTutorialHell ? "text-amber-500" : "text-emerald-500"}`}
              />
              <span className="font-mono text-xs font-semibold">
                Tutorial Hell Detector: {tutorialHell.statusText}
              </span>
            </div>
            <span className="font-mono text-xs text-muted-foreground">
              Watch Ratio: <strong className="text-foreground">{tutorialHell.ratio}x</strong>{" "}
              (Threshold 2.8x)
            </span>
          </div>

          <div className="mt-2 text-xs text-muted-foreground">
            {tutorialHell.isTutorialHell ? (
              <p className="text-amber-600 dark:text-amber-400 font-medium">
                {tutorialHell.lockedReason}
              </p>
            ) : (
              <p>
                Healthy build ratio: {tutorialHell.buildHours}h coding/executing vs{" "}
                {tutorialHell.watchHours}h reading across the past 7 days.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between">
        <Tabs value={filter} onValueChange={setFilter}>
          <TabsList>
            <TabsTrigger value="all" className="font-mono text-xs">
              All Proofs ({artifacts.length})
            </TabsTrigger>
            <TabsTrigger value="code_execution" className="font-mono text-xs">
              Code Runs
            </TabsTrigger>
            <TabsTrigger value="terminal_session" className="font-mono text-xs">
              Terminal
            </TabsTrigger>
            <TabsTrigger value="mock_interview" className="font-mono text-xs">
              Interviews
            </TabsTrigger>
            <TabsTrigger value="git_commit" className="font-mono text-xs">
              Git Commits
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* Chronological Artifacts Stream */}
      <div className="space-y-3">
        {filtered.map((item) => (
          <div
            key={item.id}
            className="rounded-xl border border-border bg-card p-4 transition-all hover:border-primary/40 shadow-sm flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"
          >
            <div className="flex items-start gap-3">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted border border-border">
                {getIcon(item.type)}
              </div>
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <h4 className="text-sm font-semibold text-foreground">{item.title}</h4>
                  <Badge variant="outline" className="font-mono text-[9px] uppercase px-1.5 py-0">
                    {item.type.replace("_", " ")}
                  </Badge>
                </div>
                <p className="text-xs text-muted-foreground">{item.summary}</p>
                <div className="flex flex-wrap items-center gap-1.5 pt-1">
                  {item.tags.map((t) => (
                    <Badge key={t} variant="secondary" className="font-mono text-[9px] px-1 py-0">
                      #{t}
                    </Badge>
                  ))}
                  {item.metrics.durationMs !== undefined && (
                    <span className="font-mono text-[10px] text-muted-foreground ml-2">
                      Latency: {item.metrics.durationMs}ms
                    </span>
                  )}
                  {item.metrics.score !== undefined && (
                    <span className="font-mono text-[10px] text-muted-foreground ml-2">
                      Score: {item.metrics.score}/100
                    </span>
                  )}
                </div>
              </div>
            </div>

            {/* Verification SHA Token Badge */}
            <div className="flex flex-row sm:flex-col items-end gap-1.5 self-end sm:self-auto shrink-0">
              <div className="flex items-center gap-1 text-emerald-500 font-mono text-[10px]">
                <CheckCircle2 className="h-3.5 w-3.5" />
                <span>VERIFIED RECEIPT</span>
              </div>
              <button
                onClick={() => handleCopySha(item.shaReceipt)}
                className="group flex items-center gap-1 rounded bg-muted/80 px-2 py-0.5 font-mono text-[10px] text-muted-foreground hover:bg-muted hover:text-foreground transition-colors border border-border/60"
                title="Click to copy receipt SHA"
              >
                <span>{item.shaReceipt}</span>
                <Copy className="h-3 w-3 opacity-60 group-hover:opacity-100" />
              </button>
              <span className="text-[10px] font-mono text-muted-foreground">
                {new Date(item.timestamp).toLocaleDateString()}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
