/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCodeLabRouteImport } from './routes/_authenticated/code-lab'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDsaRouteImport } from './routes/_authenticated/dsa'
import { Route as AuthenticatedGitRouteImport } from './routes/_authenticated/git'
import { Route as AuthenticatedLinuxRouteImport } from './routes/_authenticated/linux'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgrammingRouteImport } from './routes/_authenticated/programming'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRoadmapsRouteImport } from './routes/_authenticated/roadmaps'
import { Route as AuthenticatedSqlLabRouteImport } from './routes/_authenticated/sql-lab'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedLearnCourseSlugRouteImport } from './routes/_authenticated/learn.$courseSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCodeLabRoute = AuthenticatedCodeLabRouteImport.update({
  id: '/code-lab',
  path: '/code-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDsaRoute = AuthenticatedDsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGitRoute = AuthenticatedGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinuxRoute = AuthenticatedLinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgrammingRoute =
  AuthenticatedProgrammingRouteImport.update({
    id: '/programming',
    path: '/programming',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapsRoute = AuthenticatedRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSqlLabRoute = AuthenticatedSqlLabRouteImport.update({
  id: '/sql-lab',
  path: '/sql-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnCourseSlugRoute =
  AuthenticatedLearnCourseSlugRouteImport.update({
    id: '/learn/$courseSlug',
    path: '/learn/$courseSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/code-lab': typeof AuthenticatedCodeLabRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dsa': typeof AuthenticatedDsaRoute
  '/git': typeof AuthenticatedGitRoute
  '/linux': typeof AuthenticatedLinuxRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programming': typeof AuthenticatedProgrammingRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/sql-lab': typeof AuthenticatedSqlLabRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/code-lab': typeof AuthenticatedCodeLabRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dsa': typeof AuthenticatedDsaRoute
  '/git': typeof AuthenticatedGitRoute
  '/linux': typeof AuthenticatedLinuxRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programming': typeof AuthenticatedProgrammingRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/sql-lab': typeof AuthenticatedSqlLabRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/code-lab': typeof AuthenticatedCodeLabRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dsa': typeof AuthenticatedDsaRoute
  '/_authenticated/git': typeof AuthenticatedGitRoute
  '/_authenticated/linux': typeof AuthenticatedLinuxRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programming': typeof AuthenticatedProgrammingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/_authenticated/sql-lab': typeof AuthenticatedSqlLabRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/code-lab'
    | '/dashboard'
    | '/dsa'
    | '/git'
    | '/linux'
    | '/mentor'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/programming'
    | '/projects'
    | '/roadmaps'
    | '/sql-lab'
    | '/tasks'
    | '/learn/$courseSlug'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/code-lab'
    | '/dashboard'
    | '/dsa'
    | '/git'
    | '/linux'
    | '/mentor'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/programming'
    | '/projects'
    | '/roadmaps'
    | '/sql-lab'
    | '/tasks'
    | '/learn/$courseSlug'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/code-lab'
    | '/_authenticated/dashboard'
    | '/_authenticated/dsa'
    | '/_authenticated/git'
    | '/_authenticated/linux'
    | '/_authenticated/mentor'
    | '/_authenticated/onboarding'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/programming'
    | '/_authenticated/projects'
    | '/_authenticated/roadmaps'
    | '/_authenticated/sql-lab'
    | '/_authenticated/tasks'
    | '/_authenticated/learn/$courseSlug'
    | '/_authenticated/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/code-lab': {
      id: '/_authenticated/code-lab'
      path: '/code-lab'
      fullPath: '/code-lab'
      preLoaderRoute: typeof AuthenticatedCodeLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa': {
      id: '/_authenticated/dsa'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof AuthenticatedDsaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/git': {
      id: '/_authenticated/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof AuthenticatedGitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linux': {
      id: '/_authenticated/linux'
      path: '/linux'
      fullPath: '/linux'
      preLoaderRoute: typeof AuthenticatedLinuxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programming': {
      id: '/_authenticated/programming'
      path: '/programming'
      fullPath: '/programming'
      preLoaderRoute: typeof AuthenticatedProgrammingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmaps': {
      id: '/_authenticated/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof AuthenticatedRoadmapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sql-lab': {
      id: '/_authenticated/sql-lab'
      path: '/sql-lab'
      fullPath: '/sql-lab'
      preLoaderRoute: typeof AuthenticatedSqlLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseSlug': {
      id: '/_authenticated/learn/$courseSlug'
      path: '/learn/$courseSlug'
      fullPath: '/learn/$courseSlug'
      preLoaderRoute: typeof AuthenticatedLearnCourseSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCodeLabRoute: typeof AuthenticatedCodeLabRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDsaRoute: typeof AuthenticatedDsaRoute
  AuthenticatedGitRoute: typeof AuthenticatedGitRoute
  AuthenticatedLinuxRoute: typeof AuthenticatedLinuxRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgrammingRoute: typeof AuthenticatedProgrammingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRoadmapsRoute: typeof AuthenticatedRoadmapsRoute
  AuthenticatedSqlLabRoute: typeof AuthenticatedSqlLabRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedLearnCourseSlugRoute: typeof AuthenticatedLearnCourseSlugRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCodeLabRoute: AuthenticatedCodeLabRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDsaRoute: AuthenticatedDsaRoute,
  AuthenticatedGitRoute: AuthenticatedGitRoute,
  AuthenticatedLinuxRoute: AuthenticatedLinuxRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgrammingRoute: AuthenticatedProgrammingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRoadmapsRoute: AuthenticatedRoadmapsRoute,
  AuthenticatedSqlLabRoute: AuthenticatedSqlLabRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedLearnCourseSlugRoute: AuthenticatedLearnCourseSlugRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
